export enum CustomErrorCodes {
  USER_BLOCKED = 'user/blocked',
  VALIDATION_FAILED = 'request/validation-failed',
  UNEXPECTED_ERROR = 'server/unexpected-error',
  WRONG_OPT = 'request/wrong-opt',
  FORBIDDEN = 'user/forbidden',
  UNAUTHORIZED = 'user/unauthorized',
  SERVER_ERROR = 'server/internal-server-error',
  URL_NOT_FOUND = 'url/not-found',
  IP_BLOCKED = 'request/ip-blocked',
  INVALID_REFRESH_TOKEN = 'jwt/invalid-refresh-token',
  INVALID_DATE_FORMAT = 'logs/invalid-date-format',
  INVALID_LOG_TYPE = 'logs/invalid-log-type',
  BAD_REQUEST = 'request/bad-request',
  USER_EXIST = 'user/already-exist',
  USER_NOT_FOUND = 'user/not-found',
  SESSION_EXPIRED = 'auth/signup-request/session-expired',
  EMAIL_ALREADY_EXISTS_WITH_DIFFERENT_PHONE_NO = 'user/email-already-exists-with-different-phone-no',
  PHONE_NO_ALREADY_EXISTS_WITH_DIFFERENT_EMAIL = 'user/phone-no-already-exists-with-different-email',
  USER_NOT_ALLOWED_TO_DELETE = 'user/not-allowed-to-delete',
  PHONE_NO_NOT_CHANGED = 'user/phone-no-not-changed',
  USER_ALREADY_EXISTS = 'user/already-exists',
  INVALID_CREDENTIALS = 'user/invalid-credentials',
  MERCHANT_NOT_VERIFIED_IN_SE = 'merchant/not-verified-in-suitable-eats',
}
