export enum MerchantEventType {
  SUCCESSFULLY_APPLIED_FOR_MERCHANT_ENROLLMENT = 'SUCCESSFULLY_APPLIED_FOR_MERCHANT_ENROLLMENT',
  MERCHANT_ACCOUNT_APPROVED = 'MERCHANT_ACCOUNT_APPROVED',
  MERCHANT_VERIFICATION_FAILED = 'MERCHANT_VERIFICATION_FAILED',
}
