export enum DriverProfileEventType {
  UNAVAILABLE_DRIVER = 'UNAVAILABLE_DRIVER',
  DRIVER_DOCS_VERIFICATION_STATUS_UPDATE = 'DRIVER_DOCS_VERIFICATION_STATUS_UPDATE',
  DRIVER_REGISTERED = 'DRIVER_REGISTERED',
}
